/**
 * Convenience aliases over the generated `Database` type.
 *
 * `database.types.ts` is generated by the Supabase CLI — do not hand-edit it.
 * Regenerate with:
 *
 *   npx supabase gen types typescript --project-id plvosxnepmhbamjpjoxr \
 *     > packages/api/src/database.types.ts
 */
import type { Database } from "./database.types.ts";

export type { Database, Json } from "./database.types.ts";

type PublicSchema = Database["public"];
type Tables = PublicSchema["Tables"];
type Enums = PublicSchema["Enums"];
type Functions = PublicSchema["Functions"];

/* ------------------------------------------------------------------- rows */

export type TenantRow = Tables["tenants"]["Row"];
export type TenantSettingsRow = Tables["tenant_settings"]["Row"];

export type TemplateRow = Tables["templates"]["Row"];
export type TemplateVariantRow = Tables["template_variants"]["Row"];

export type EventRow = Tables["events"]["Row"];
export type EventTemplateRow = Tables["event_templates"]["Row"];

export type AlbumRow = Tables["albums"]["Row"];
export type AlbumPhotoRow = Tables["album_photos"]["Row"];

export type AppContentRow = Tables["app_content"]["Row"];

export type PrintJobRow = Tables["print_jobs"]["Row"];
export type ShareLinkRow = Tables["share_links"]["Row"];
export type DeliveryRow = Tables["deliveries"]["Row"];
export type SessionRow = Tables["sessions"]["Row"];
export type InquiryRow = Tables["inquiries"]["Row"];

/* ---------------------------------------------------------------- inserts */

export type TemplateInsert = Tables["templates"]["Insert"];
export type EventInsert = Tables["events"]["Insert"];
export type AlbumInsert = Tables["albums"]["Insert"];

/* ------------------------------------------------------------------ enums */

export type PublishStatus = Enums["publish_status"];
export type EventStatus = Enums["event_status"];
export type EventVisibility = Enums["event_visibility"];
export type StaffRole = Enums["staff_role"];
export type StaffStatus = Enums["staff_status"];
export type PrintStatus = Enums["print_status"];
export type DeliveryChannel = Enums["delivery_channel"];
export type DeliveryStatus = Enums["delivery_status"];
export type CaptureSurface = Enums["capture_surface"];
export type InquiryStatus = Enums["inquiry_status"];

/* --------------------------------------------------------------- rpc rows */

/** Row shape returned by the `live_events(uuid)` Postgres function. */
export type LiveEventRow = Functions["live_events"]["Returns"][number];
