/**
 * Builds a seed migration for PXLPOD's three real templates.
 *
 * Slot geometry comes from tools/detect_slots.py measuring the actual alpha
 * channels — nothing here is typed by hand, so the database agrees with the
 * artwork by construction.
 *
 *   node tools/seed_templates.mjs
 *   supabase db push
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const TENANT = "9e605b70-4e7f-4aec-ade9-84c20b69d20d";
const detected = JSON.parse(
  readFileSync(resolve("packages/template-spec/fixtures/detected-slots.json"), "utf8"),
);

/**
 * The one thing detection cannot decide. A 2x2 sheet of four distinct photos
 * and a 4x2 strip that repeats four photos in two cut-apart columns are
 * geometrically identical, so the operator settles it — here, standing in for
 * the toggle in the console's Slot Mapper.
 */
const TEMPLATES = [
  {
    key: "single strip/SS-White.png",
    name: "Single strip",
    description: "Four shots on a white 4-up film sheet.",
    category: "classic",
    dir: "single-strip",
    duplicateColumns: false,
  },
  {
    key: "double strip/DS-White.png",
    name: "Double strip",
    description: "Four shots printed twice, cut down the middle into two strips.",
    category: "strip",
    dir: "double-strip",
    duplicateColumns: true,
  },
  {
    key: "fish eye/2026-FS-SS-White.png",
    name: "Fish eye",
    description: "Four shots in circular windows, cut for the high-angle lens.",
    category: "fisheye",
    dir: "fish-eye",
    duplicateColumns: false,
  },
];

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const statements = TEMPLATES.map((t) => {
  const src = detected[t.key];
  if (!src) throw new Error(`No detection data for ${t.key}`);

  const slots = src.slots.map((s, i) => ({
    id: s.id,
    // Paired left/right windows share a shot on a cut-apart strip.
    photoIndex: t.duplicateColumns ? Math.floor(i / 2) : i,
    x: s.x,
    y: s.y,
    w: s.w,
    h: s.h,
    shape: s.shape,
    cornerRadius: 0,
    rotation: 0,
    fit: "cover",
    mirror: false,
  }));

  const shotCount = new Set(slots.map((s) => s.photoIndex)).size;

  const spec = {
    version: 1,
    tenantId: TENANT,
    name: t.name,
    description: t.description,
    category: t.category,
    canvas: {
      width: src.canvas.width,
      height: src.canvas.height,
      dpi: 300,
      background: "#FFFFFF",
    },
    slots,
    layers: [
      { id: "overlay", type: "image", z: 10, src: `${TENANT}/${t.dir}/white.png`, opacity: 1 },
    ],
    variants: [
      {
        id: "white",
        label: "White",
        overlay: `${TENANT}/${t.dir}/white.png`,
        textColor: "#14140F",
        isDefault: true,
      },
      {
        id: "black",
        label: "Black",
        overlay: `${TENANT}/${t.dir}/black.png`,
        textColor: "#F5F5F0",
        isDefault: false,
      },
    ],
    capture: { defaultTimer: 3, allowRetakePerShot: true, allowedFilters: [] },
    gif: { enabled: true, width: 600, fps: 4, boomerang: true },
    printable: true,
  };

  const variantRows = spec.variants
    .map(
      (v, i) =>
        `    (tid, ${q(v.label)}, ${q(v.overlay)}, ${q(v.textColor)}, ${v.isDefault}, ${i})`,
    )
    .join(",\n");

  return `
-- ${t.name}: ${slots.length} window${slots.length === 1 ? "" : "s"}, ${shotCount} shot${shotCount === 1 ? "" : "s"}${
    t.duplicateColumns ? " (columns duplicated, cut apart after printing)" : ""
  }
do $$
declare tid uuid;
begin
  insert into public.templates
    (tenant_id, name, description, category, spec, shot_count, printable, status, published_at)
  values
    (${q(TENANT)}::uuid, ${q(t.name)}, ${q(t.description)}, ${q(t.category)},
     ${q(JSON.stringify(spec))}::jsonb, ${shotCount}, true, 'published', now())
  returning id into tid;

  insert into public.template_variants (template_id, label, overlay_path, text_color, is_default, sort)
  values
${variantRows};
end $$;`;
}).join("\n");

const sql = `-- Seed: PXLPOD's three production templates.
--
-- Generated by tools/seed_templates.mjs from the alpha-channel measurements in
-- packages/template-spec/fixtures/detected-slots.json. Do not hand-edit the
-- geometry here; change the artwork, re-run detection, regenerate.
${statements}
`;

const stamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
const out = `supabase/migrations/${stamp}_seed_pxlpod_templates.sql`;
writeFileSync(out, sql);
console.log(`wrote ${out}`);
for (const t of TEMPLATES) {
  const s = detected[t.key];
  const shots = t.duplicateColumns ? s.slots.length / 2 : s.slots.length;
  console.log(
    `  ${t.name.padEnd(14)} ${String(s.slots.length).padStart(2)} windows -> ${shots} shots  ${s.slots[0].shape}`,
  );
}
