-- Seed: PXLPOD's three production templates.
--
-- Generated by tools/seed_templates.mjs from the alpha-channel measurements in
-- packages/template-spec/fixtures/detected-slots.json. Do not hand-edit the
-- geometry here; change the artwork, re-run detection, regenerate.

-- Single strip: 4 windows, 4 shots
do $$
declare tid uuid;
begin
  insert into public.templates
    (tenant_id, name, description, category, spec, shot_count, printable, status, published_at)
  values
    ('9e605b70-4e7f-4aec-ade9-84c20b69d20d'::uuid, 'Single strip', 'Four shots on a white 4-up film sheet.', 'classic',
     '{"version":1,"tenantId":"9e605b70-4e7f-4aec-ade9-84c20b69d20d","name":"Single strip","description":"Four shots on a white 4-up film sheet.","category":"classic","canvas":{"width":1200,"height":1800,"dpi":300,"background":"#FFFFFF"},"slots":[{"id":"s1","photoIndex":0,"x":79,"y":164,"w":509,"h":715,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s2","photoIndex":1,"x":614,"y":164,"w":509,"h":715,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s3","photoIndex":2,"x":79,"y":921,"w":509,"h":715,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s4","photoIndex":3,"x":614,"y":921,"w":509,"h":715,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true}],"layers":[{"id":"overlay","type":"image","z":10,"src":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/single-strip/white.png","opacity":1}],"variants":[{"id":"white","label":"White","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/single-strip/white.png","textColor":"#14140F","isDefault":true},{"id":"black","label":"Black","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/single-strip/black.png","textColor":"#F5F5F0","isDefault":false}],"capture":{"defaultTimer":3,"allowRetakePerShot":true,"allowedFilters":[]},"gif":{"enabled":true,"width":600,"fps":4,"boomerang":true},"printable":true}'::jsonb, 4, true, 'published', now())
  returning id into tid;

  insert into public.template_variants (template_id, label, overlay_path, text_color, is_default, sort)
  values
    (tid, 'White', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/single-strip/white.png', '#14140F', true, 0),
    (tid, 'Black', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/single-strip/black.png', '#F5F5F0', false, 1);
end $$;

-- Double strip: 8 windows, 4 shots (columns duplicated, cut apart after printing)
do $$
declare tid uuid;
begin
  insert into public.templates
    (tenant_id, name, description, category, spec, shot_count, printable, status, published_at)
  values
    ('9e605b70-4e7f-4aec-ade9-84c20b69d20d'::uuid, 'Double strip', 'Four shots printed twice, cut down the middle into two strips.', 'strip',
     '{"version":1,"tenantId":"9e605b70-4e7f-4aec-ade9-84c20b69d20d","name":"Double strip","description":"Four shots printed twice, cut down the middle into two strips.","category":"strip","canvas":{"width":1200,"height":1800,"dpi":300,"background":"#FFFFFF"},"slots":[{"id":"s1","photoIndex":0,"x":47,"y":54,"w":532,"h":394,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s2","photoIndex":0,"x":621,"y":54,"w":531,"h":394,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s3","photoIndex":1,"x":47,"y":472,"w":531,"h":393,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s4","photoIndex":1,"x":621,"y":472,"w":531,"h":393,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s5","photoIndex":2,"x":47,"y":935,"w":531,"h":393,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s6","photoIndex":2,"x":621,"y":935,"w":531,"h":393,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s7","photoIndex":3,"x":47,"y":1352,"w":531,"h":394,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s8","photoIndex":3,"x":621,"y":1352,"w":531,"h":394,"shape":"rect","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true}],"layers":[{"id":"overlay","type":"image","z":10,"src":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/double-strip/white.png","opacity":1}],"variants":[{"id":"white","label":"White","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/double-strip/white.png","textColor":"#14140F","isDefault":true},{"id":"black","label":"Black","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/double-strip/black.png","textColor":"#F5F5F0","isDefault":false}],"capture":{"defaultTimer":3,"allowRetakePerShot":true,"allowedFilters":[]},"gif":{"enabled":true,"width":600,"fps":4,"boomerang":true},"printable":true}'::jsonb, 4, true, 'published', now())
  returning id into tid;

  insert into public.template_variants (template_id, label, overlay_path, text_color, is_default, sort)
  values
    (tid, 'White', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/double-strip/white.png', '#14140F', true, 0),
    (tid, 'Black', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/double-strip/black.png', '#F5F5F0', false, 1);
end $$;

-- Fish eye: 4 windows, 4 shots
do $$
declare tid uuid;
begin
  insert into public.templates
    (tenant_id, name, description, category, spec, shot_count, printable, status, published_at)
  values
    ('9e605b70-4e7f-4aec-ade9-84c20b69d20d'::uuid, 'Fish eye', 'Four shots in circular windows, cut for the high-angle lens.', 'fisheye',
     '{"version":1,"tenantId":"9e605b70-4e7f-4aec-ade9-84c20b69d20d","name":"Fish eye","description":"Four shots in circular windows, cut for the high-angle lens.","category":"fisheye","canvas":{"width":1200,"height":1800,"dpi":300,"background":"#FFFFFF"},"slots":[{"id":"s1","photoIndex":0,"x":43,"y":240,"w":544,"h":522,"shape":"circle","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s2","photoIndex":1,"x":606,"y":240,"w":551,"h":522,"shape":"circle","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s3","photoIndex":2,"x":43,"y":785,"w":544,"h":556,"shape":"circle","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true},{"id":"s4","photoIndex":3,"x":606,"y":785,"w":551,"h":556,"shape":"circle","cornerRadius":0,"rotation":0,"fit":"cover","mirror":true}],"layers":[{"id":"overlay","type":"image","z":10,"src":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/fish-eye/white.png","opacity":1}],"variants":[{"id":"white","label":"White","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/fish-eye/white.png","textColor":"#14140F","isDefault":true},{"id":"black","label":"Black","overlay":"9e605b70-4e7f-4aec-ade9-84c20b69d20d/fish-eye/black.png","textColor":"#F5F5F0","isDefault":false}],"capture":{"defaultTimer":3,"allowRetakePerShot":true,"allowedFilters":[]},"gif":{"enabled":true,"width":600,"fps":4,"boomerang":true},"printable":true}'::jsonb, 4, true, 'published', now())
  returning id into tid;

  insert into public.template_variants (template_id, label, overlay_path, text_color, is_default, sort)
  values
    (tid, 'White', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/fish-eye/white.png', '#14140F', true, 0),
    (tid, 'Black', '9e605b70-4e7f-4aec-ade9-84c20b69d20d/fish-eye/black.png', '#F5F5F0', false, 1);
end $$;
